# Generated by Django 6.1 on 2026-08-23 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('download_type', models.CharField(max_length=10)),
                ('quality', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=20)),
                ('stage', models.CharField(default='Waiting for a worker', max_length=100)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('downloaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('eta', models.PositiveIntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
