# Generated by Django 6.1 on 2026-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
