# Generated by Django 6.1 on 2026-08-23 22:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_downloadjob_status_alter_downloadjob_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal campaign name', max_length=100)),
                ('placement', models.CharField(choices=[('page_top', 'Top of page'), ('above_form', 'Above download form'), ('below_form', 'Below download form')], db_index=True, max_length=20)),
                ('headline', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('image_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))])),
                ('destination_url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))])),
                ('disclosure', models.CharField(default='Sponsored / Affiliate link', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('impressions', models.PositiveBigIntegerField(default=0, editable=False)),
                ('clicks', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
